services:
  dev-env:
    image: tensorflow/tensorflow:latest-gpu
    ports:
      - "8888:8888"
    volumes:
      - ./Project:/Volume
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    working_dir: /Volume