services:

  experience-store:
    build:
      dockerfile: ./src/ExperienceStore/Dockerfile
    image: experience-store

    volumes:
      # add output dictionary for the learned data
      - ML_Data:/app/Data

      # dictionaries for dev
      - ./src:/app/src
      - ./Config:/app/Config

    working_dir: /app
    networks:
      - projectNetwork
    expose:
      - 5001

    entrypoint: python main.py --subsystem ExperienceStore --env /app/Config/Envs/FrozenLake.json

  model-store:
    image: redis

    volumes:
      - ML_Data:/data

    networks:
      - projectNetwork
    expose:
      - 5002

    entrypoint: redis-server --port 5002 # --save 60 1

  web-server:
    build:
      dockerfile: ./src/WebServer/Dockerfile
    image: web-server

    volumes:
      # dictionaries for dev
      - ./src:/app/src
      - ./Config:/app/Config

    working_dir: /app
    networks:
      - projectNetwork
    ports:
      - "5000:5000"

    entrypoint: python main.py --subsystem Webserver --env /app/Config/Envs/FrozenLake.json

  worker:
    build:
      dockerfile: ./src/Worker/Dockerfile
    image: worker

    volumes:
      # add output dictionary for the learned data
      - ML_Data:/app/Data

      # dictionaries for dev
      - ./src:/app/src
      - ./Config:/app/Config


    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    working_dir: /app
    networks:
      - projectNetwork

    entrypoint: python main.py --subsystem Worker --env /app/Config/Envs/FrozenLake.json

  learner:
    build:
      dockerfile: ./src/Learner/Dockerfile
    image: learner

    volumes:
      # add output dictionary for the learned data
      - ML_Data:/app/Data

      # dictionaries for dev
      - ./src:/app/src
      - ./Config:/app/Config


    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    working_dir: /app
    networks:
      - projectNetwork

    entrypoint: python main.py --subsystem Learner --model Policy --env /app/Config/Envs/FrozenLake.json


volumes:
  ML_Data:
networks:
  projectNetwork: