name: Tests

on:
  - push

defaults:
  run:
    working-directory: Project

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.10
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: LintChecks
        run: flake8 src/ --config=config.ini

      - name: LintChecks-Tests
        run: flake8 Tests/ --config=config.ini