name: Tests

on:
  - push
  # - pull_request

defaults:
  run:
    working-directory: Project

jobs:
  Setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

  CheckTypeHints:
    Needs: Setup
    run: |
      python -m mypy Scripts/Main.py --config-file Tests/mypy.ini --install-types
  UnitTests:
    Needs: Setup
    run: |
      unittest-parallel -q
  Lint:
    Needs: Setup
    run: |
      flake8