name: Tests

on:
  - push
  # - pull_request

defaults:
  run:
    working-directory: Project

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

  TypeChecks:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Check Type Hints
        run: |
          python -m mypy Scripts/Main.py --config-file Tests/mypy.ini --install-types

  UnitTests:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: UnitTest
        run: |
          unittest-parallel -q

  LintChecks:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: LintChecks
        run: |
          flake8